#pragma once

#include <AnalysisPlugin.h>

#include <PointData/PointData.h>

#include "SettingsAction.h"

#define UMAPPP_CUSTOM_NEIGHBORS // due to an older hsnw version in knncolle
#include "umappp/Umap.hpp"
#undef UMAPPP_CUSTOM_NEIGHBORS

#include <memory>

using namespace mv::plugin;
using namespace mv;

/**
 * UMAP analysis plugin class
 *
 * This analysis plugin class provides acces to the UMAP implementation from
 * https://github.com/LTLA/umappp as an analysis plugin in HDPS
 *
 * UMAP is a neighborhood-based dimensionality reduction similar to t-SNE
 *
 * @authors T. Höllt, A.Vieth
 */
class UMAPAnalysisPlugin : public AnalysisPlugin
{
Q_OBJECT

public:
    using scalar_t      = float;
    using UMAP          = umappp::Umap<scalar_t>;
    using UMAP_STATUS   = std::unique_ptr<UMAP::Status>;

    UMAPAnalysisPlugin(const PluginFactory* factory);
    ~UMAPAnalysisPlugin() override = default;

    void init() override;

private:
    SettingsAction          _settingsAction;    /** The place where settings are stored (more info in SettingsAction.h) */
    std::vector<float>      _embedding;         /** The output embedding as generated by this plugin  */
    int                     _outDimensions;     /** The number of dimensions to reduce to */
    Dataset<Points>         _outputPoints;
    
    UMAP                    _umap;
    UMAP_STATUS             _umapStatus;
    bool                    _shouldStop;
};

/**
 * UMAP analysis plugin factory class
 */
class UMAPAnalysisPluginFactory : public AnalysisPluginFactory
{
    Q_INTERFACES(mv::plugin::AnalysisPluginFactory mv::plugin::PluginFactory)
    Q_OBJECT
    Q_PLUGIN_METADATA(IID   "studio.manivault.UMAPAnalysisPlugin"
                      FILE  "UMAPAnalysisPlugin.json")

public:

    UMAPAnalysisPluginFactory() {}
    ~UMAPAnalysisPluginFactory() override {}

    QIcon getIcon(const QColor& color = Qt::black) const override;

    /** Creates an instance of the UMAP analysis plugin */
    AnalysisPlugin* produce() override;

    /** Returns the data types that are supported by the UMAP analysis plugin */
    mv::DataTypes supportedDataTypes() const override;

    /** Enable right-click on data set to open analysis */
    PluginTriggerActions getPluginTriggerActions(const mv::Datasets& datasets) const override;
};
